# Site settings
title:       melgenek
author:      Yev Melnyk
description: "melgenek's blog"
baseurl:     ""
url:         "https://melgenek.dev"
date_format: "%-d %B %Y"

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics:

cloudflare_beacon_token: "72a450cd6ee143938b9f1031f4411600"

# Optional features
show_social_icons:    true
extended_fonts: true

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: melgenek-github-io

# Social icons
github_username: melgenek
linkedin_username: yevhenii-melnyk

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  post:
    updated:  'Updated'
    words:    'words'
  index:
    coming_soon: 'Coming soon...'
  og_locale: 'en_US'

# Build settings
markdown:     kramdown
kramdown:
  parse_block_html: true

permalink:    :title
paginate:     4
paginate_path: /page/:num

sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - screenshot.png
  - vendor
  - .idea
